Fix User-Agent set with headers
rakyll/hey pull request #209
Opened 2020-05-30 19:51 UTC by spk

on command line the option -H "User-Agent: CustomUserAgent"
is ignored and default user agent is always used
First check if its defined then fallback to default

ref https://github.com/rakyll/hey/pull/87
fix https://github.com/rakyll/hey/issues/157

2021-01-02 11:51 UTC, lupguo approved these changes
check completed, no problem

2021-01-02 11:51 UTC, lupguo reviewed
check completed, no problem

2021-01-02 11:53 UTC, lupguo requested changes
Check done

2021-09-01 12:59 UTC, spk commented
ref https://github.com/rakyll/hey/commit/898582754e00405372f0686641441168f4e2f489

2021-09-01 12:59 UTC, closed without merging